name: Scrape MaxPreps → JSON → Pages

on:
  schedule:
    - cron: "0 8 * * *"   # jalan tiap hari 08:00 UTC (≈ 04:00 ET)
  workflow_dispatch:
    inputs:
      date:
        description: "Date mm/dd/YYYY (MaxPreps format, US)"
        required: false
        default: ""
      states:
        description: "Comma-separated states (e.g. tx,ca,fl). Empty = all"
        required: false
        default: ""

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "scrape-pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York   # tanggal acuan ET (cocokkan dg frontend)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # <— perlu untuk commit balik

      - name: Set Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scraper/requirements.txt

      - name: Resolve date & states (US ET)
        id: args
        run: |
          if [ -n "${{ github.event.inputs.date }}" ]; then
            DATE_IN="${{ github.event.inputs.date }}"
          else
            DATE_IN=$(date +"%m/%d/%Y")
          fi
          STATES_IN="${{ github.event.inputs.states }}"
          echo "date=${DATE_IN}" >> $GITHUB_OUTPUT
          echo "states=${STATES_IN}" >> $GITHUB_OUTPUT
          echo "Using ET date=$DATE_IN states=$STATES_IN"

      - name: Run scraper (today)
        run: |
          mkdir -p data
          python scraper/maxpreps_to_json.py \
            --date "${{ steps.args.outputs.date }}" \
            $([ -n "${{ steps.args.outputs.states }}" ] && echo --states "${{ steps.args.outputs.states }}") \
            --outdir "data"

      # ===== Persist hasil ke repo (biar file lama tetap ada) =====
      - name: Persist data to repo
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A data
          git commit -m "data: update feeds for ${{ steps.args.outputs.date || 'today(ET)' }} ${ { steps.args.outputs.states } }" || echo "no changes"
          git push

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # deploy seluruh repo (termasuk data/ yang baru di-commit)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
