name: Scrape MaxPreps → JSON → Pages

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Tanggal (mm/dd/YYYY)"
        required: true
        default: "10/03/2025"
      states:
        description: "Kode state dipisah koma (kosong = semua)"
        required: false
        default: ""

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "scrape-pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install -r scraper/requirements.txt

      # >>> INI YANG DITANYAKAN <<<
      - name: Install Playwright browsers
        run: python -m playwright install --with-deps chromium

      - name: Parse inputs
        id: args
        run: |
          echo "date=${{ github.event.inputs.date }}" >> $GITHUB_OUTPUT
          echo "states=${{ github.event.inputs.states }}" >> $GITHUB_OUTPUT

      - name: Run scraper
        run: |
          python scraper/maxpreps_to_json.py \
            --date "${{ steps.args.outputs.date }}" \
            $([ -n "${{ steps.args.outputs.states }}" ] && echo --states "${{ steps.args.outputs.states }}") \
            --outdir data

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
