name: Scrape MaxPreps → JSON → Pages

on:
  workflow_dispatch:
    inputs:
      date:
        description: 'Tanggal (mm/dd/YYYY), contoh: 10/03/2025'
        required: true
        default: '10/03/2025'
      states:
        description: 'Kode state dipisah koma (kosong = semua), contoh: nj,wy,tx'
        required: false
        default: ''
  # (Opsional) Otomatis tiap Jumat 21:00 UTC (~17:00 ET saat DST)
  schedule:
    - cron: '0 21 * * FRI'

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: scrape-pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('scraper/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: msplaywright-${{ runner.os }}-chromium

      - name: Install Python deps
        run: pip install -r scraper/requirements.txt

      - name: Install Playwright browsers (Chromium)
        run: python -m playwright install --with-deps chromium

      - name: Parse inputs
        id: args
        run: |
          echo "date=${{ github.event.inputs.date }}" >> $GITHUB_OUTPUT
          echo "states=${{ github.event.inputs.states }}" >> $GITHUB_OUTPUT

      # NOTE: kalau mau testing cepat, bisa tambahkan env di bawah:
      #   env:
      #     LIMIT_PER_STATE: "20"
      #     NO_PLAYWRIGHT: "1"
      - name: Run scraper
        run: |
          set -e
          python scraper/maxpreps_to_json.py \
            --date "${{ steps.args.outputs.date }}" \
            $([ -n "${{ steps.args.outputs.states }}" ] && echo --states "${{ steps.args.outputs.states }}") \
            --outdir data
          echo "==== List data/ ===="
          ls -lah data || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
